let DB,NUTRITION,WEIGHT,CARDIO;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtDate=iso=>iso?new Date(`${iso}T12:00:00`).toLocaleDateString('it-IT'):'—';
const setText=(s,e)=>s.kg==null?`${s.reps} reps`:`${s.kg} kg × ${s.reps}${e.perLeg?' /gamba':''}`;
function exHTML(e){return `<div class="exercise"><div><b>${e.name}</b>${e.note?`<div class="muted">${e.note}</div>`:''}</div><div class="sets">${e.sets.map(s=>`<span class="set">${setText(s,e)}</span>`).join('')}</div></div>`}
function sumDay(day){return (day?.meals||[]).reduce((a,m)=>({energy:a.energy+(m.energy||0),protein:a.protein+(m.protein||0),carbs:a.carbs+(m.carbs||0),fat:a.fat+(m.fat||0)}),{energy:0,protein:0,carbs:0,fat:0})}
function dayTotals(day){return day?.totals||sumDay(day)}
function latestNutrition(){return (NUTRITION?.days||[]).slice().sort((a,b)=>b.date.localeCompare(a.date))[0]}
function latestWorkout(){return (DB?.sessions||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0]}
function latestWeight(){return (WEIGHT?.entries||[]).slice().sort((a,b)=>b.date.localeCompare(a.date))[0]}
function latestCardio(){return (CARDIO?.activities||[]).slice().sort((a,b)=>(b.start_datetime||b.date||'').localeCompare(a.start_datetime||a.date||''))[0]}

function render(){
 const sessions=DB.sessions||[], sets=sessions.reduce((n,s)=>n+s.exercises.reduce((m,e)=>m+e.sets.length,0),0), reps=sessions.reduce((n,s)=>n+s.exercises.reduce((m,e)=>m+e.sets.reduce((q,x)=>q+(x.reps||0),0),0),0);
 const lw=latestWorkout(), ln=latestNutrition(), wt=latestWeight(), ca=CARDIO?.activities||[];
 $('#stats').innerHTML=[['Sedute',sessions.length],['Serie',sets],['Cardio',ca.length],['Peso',wt?`${wt.kg} kg`:'—']].map(x=>`<div class="stat"><b>${x[1]}</b><span class="muted">${x[0]}</span></div>`).join('');
 if(lw){$('#latestTitle').textContent=lw.label;$('#latest').innerHTML=lw.exercises.map(exHTML).join('');$('#latestTitleTraining').textContent=lw.label;$('#latestTraining').innerHTML=lw.exercises.map(exHTML).join('')}
 renderNutrition(); renderTraining(); renderWeight(); renderCardio();
 drawCalories('kcalChart'); drawCalories('kcalChartNutrition'); drawWeight('weightChart'); drawWeight('weightChartFull');
 if(ln){const t=dayTotals(ln);$('#dashDate').textContent=fmtDate(ln.date);$('#dashMacros').innerHTML=macroCards(t);$('#dashTargetNote').textContent=`Target: ${NUTRITION.targets.energy} kcal • P ${NUTRITION.targets.protein} g • C ${NUTRITION.targets.carbs} g • G ${NUTRITION.targets.fat} g`}
}
function macroCards(t){const arr=[['kcal',Math.round(t.energy||0),'kcal'],['Proteine',Math.round(t.protein||0),'g'],['Carbo',Math.round(t.carbs||0),'g'],['Grassi',Math.round(t.fat||0),'g']];return arr.map(x=>`<div class="macro"><span class="muted">${x[0]}</span><b>${x[1]} ${x[2]}</b></div>`).join('')}
function renderNutrition(){
 const day=latestNutrition(), t=dayTotals(day), g=NUTRITION.targets||{};
 $('#nutritionDate').textContent=day?fmtDate(day.date):'—'; $('#nutritionTotals').innerHTML=macroCards(t);
 const targets=[['Calorie',g.energy,'kcal'],['Proteine',g.protein,'g'],['Carboidrati',g.carbs,'g'],['Grassi',g.fat,'g']];
 $('#nutritionTargets').innerHTML=targets.map(x=>`<div class="target"><span class="muted">${x[0]}</span><b>${x[1]} ${x[2]}</b></div>`).join('');
 $('#targetExplanation').textContent=g.note||'';
 const rows=[['Calorie',t.energy,g.energy,'kcal'],['Proteine',t.protein,g.protein,'g'],['Carboidrati',t.carbs,g.carbs,'g'],['Grassi',t.fat,g.fat,'g']];
 $('#nutritionProgress').innerHTML=rows.map(([n,v,target,u])=>{const pct=target?Math.round(v/target*100):0;return `<div class="progress-row"><div class="progress-label"><span>${n}</span><span>${Math.round(v||0)} / ${target} ${u} · ${pct}%</span></div><div class="progress-track"><div class="progress-fill ${pct>110?'over':''}" style="width:${Math.min(pct,100)}%"></div></div></div>`}).join('');
 $('#nutritionMeals').innerHTML=day?.meals?.length?day.meals.map(m=>`<div class="meal"><div class="meal-head"><b>${m.type||'Pasto'}</b><span>${Math.round(m.energy||0)} kcal</span></div><div>${m.description||''}</div><div class="meal-macros">P ${Math.round(m.protein||0)} g • C ${Math.round(m.carbs||0)} g • G ${Math.round(m.fat||0)} g${m.estimated?' • stima':''}</div>${m.assumptions?`<div class="muted">${m.assumptions}</div>`:''}</div>`).join(''):'<p class="muted">Nessun pasto registrato.</p>';
 $('#nutritionHistory').innerHTML=(NUTRITION.days||[]).map(d=>{const x=dayTotals(d);return `<div class="session"><b>${fmtDate(d.date)}</b><div class="muted">${Math.round(x.energy||0)} kcal • P ${Math.round(x.protein||0)} g • C ${Math.round(x.carbs||0)} g • G ${Math.round(x.fat||0)} g • ${(d.meals||[]).length} pasti</div></div>`}).join('');
}
function renderTraining(){
 $('#program').innerHTML=Object.entries(DB.program||{}).map(([k,v])=>`<div class="day"><b>Giorno ${k}</b>${v.map(x=>`<div class="prog"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`).join('');
 renderSessions(''); const names=[...new Set((DB.sessions||[]).flatMap(s=>s.exercises.map(e=>e.name)))].sort(); $('#exerciseSelect').innerHTML=names.map(n=>`<option>${n}</option>`).join(''); $('#exerciseSelect').value=names.includes('Panca piana manubri')?'Panca piana manubri':names[0]; if(names.length)drawExercise($('#exerciseSelect').value);
}
function renderSessions(q){q=(q||'').toLowerCase();$('#sessions').innerHTML=(DB.sessions||[]).filter(s=>!q||s.label.toLowerCase().includes(q)||s.exercises.some(e=>e.name.toLowerCase().includes(q))).map(s=>`<article class="session"><b>${s.label}</b><div class="muted">${s.date?fmtDate(s.date):'Data non recuperata'} • ${s.location}</div>${s.exercises.map(exHTML).join('')}</article>`).join('')}
function renderWeight(){const entries=(WEIGHT.entries||[]).slice().sort((a,b)=>b.date.localeCompare(a.date)), w=entries[0]; $('#currentWeight').textContent=w?`${w.kg} kg`:'nessun dato'; $('#weightHeadline').textContent=w?`${w.kg} kg · ${fmtDate(w.date)}`:'Nessuna misura'; $('#weightHistory').innerHTML=entries.length?entries.map(e=>`<div class="session"><b>${fmtDate(e.date)}</b><div class="muted">${e.kg} kg${e.note?` • ${e.note}`:''}</div></div>`).join(''):'<p class="muted">Quando mi comunichi la prima pesata comparirà qui.</p>'}
function cardioRow(a){return `<div class="session"><b>${fmtDate(a.date)} · ${a.type||'Cardio'}</b><div class="muted">${a.distance_km??'—'} km • ${a.pace||'—'} min/km • ${a.speed_kmh??'—'} km/h • ${a.energy_kcal??'—'} kcal</div><div class="muted">${a.source||''}${a.route_id?' • GPS/route disponibile':''}</div></div>`}
function renderCardio(){const entries=(CARDIO?.activities||[]).slice().sort((a,b)=>(b.start_datetime||b.date||'').localeCompare(a.start_datetime||a.date||'')), c=entries[0]; $('#cardioHeadline').textContent=c?`${c.distance_km} km · ${c.pace||'—'} min/km`:'Nessuna attività'; $('#cardioLatest').innerHTML=c?cardioRow(c):'<p class="muted">Nessuna attività cardio registrata.</p>'; $('#cardioHistory').innerHTML=entries.length?entries.map(cardioRow).join(''):'<p class="muted">Nessuna attività cardio registrata.</p>'; $('#cardioSyncStatus').textContent=CARDIO?.meta?.sync_source?'MapMyRun collegato':'Sync predisposta'; drawCardioDistance(); drawCardioPace()}

function prepCanvas(id){const c=document.getElementById(id);if(!c||!c.offsetParent)return null;const dpr=devicePixelRatio||1,w=c.clientWidth||500,h=parseInt(c.getAttribute('height'))||240;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);return {ctx,w,h}}
function lineChart(id,points,opt={}){const o=prepCanvas(id);if(!o)return;const {ctx,w,h}=o;ctx.font='12px system-ui';ctx.fillStyle='#94a3b8';if(!points.length){ctx.fillText(opt.empty||'Nessun dato disponibile.',20,30);return}const p={l:52,r:18,t:24,b:38},W=w-p.l-p.r,H=h-p.t-p.b,vals=points.map(x=>x.value),extra=opt.target?[opt.target]:[],min0=Math.min(...vals,...extra),max0=Math.max(...vals,...extra),pad=Math.max(.1,(max0-min0)*.15),min=opt.zero?0:Math.max(0,min0-pad),max=max0+pad,span=Math.max(.1,max-min);ctx.strokeStyle='#263249';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=p.t+H*i/3;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(p.l+W,y);ctx.stroke();const v=max-(max-min)*i/3;ctx.fillStyle='#94a3b8';ctx.fillText((opt.decimals? v.toFixed(opt.decimals):Math.round(v)),p.l-42,y+4)}if(opt.target){const y=p.t+H-(opt.target-min)/span*H;ctx.save();ctx.setLineDash([6,5]);ctx.strokeStyle='#fbbf24';ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(p.l+W,y);ctx.stroke();ctx.restore()}ctx.strokeStyle='#a7f3d0';ctx.lineWidth=3;ctx.beginPath();points.forEach((x,i)=>{const xx=p.l+(points.length===1?W/2:W*i/(points.length-1)),yy=p.t+H-(x.value-min)/span*H;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();points.forEach((x,i)=>{const xx=p.l+(points.length===1?W/2:W*i/(points.length-1)),yy=p.t+H-(x.value-min)/span*H;ctx.fillStyle='#a7f3d0';ctx.beginPath();ctx.arc(xx,yy,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#94a3b8';ctx.fillText(x.label,Math.max(4,xx-22),h-12)})}
function drawCalories(id){const pts=(NUTRITION.days||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)).map(d=>({label:fmtDate(d.date).slice(0,5),value:Math.round(dayTotals(d).energy||0)}));lineChart(id,pts,{target:NUTRITION.targets?.energy,zero:true,empty:'Nessun giorno registrato.'})}
function drawWeight(id){const pts=(WEIGHT.entries||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({label:fmtDate(e.date).slice(0,5),value:e.kg}));lineChart(id,pts,{empty:'Registra la prima pesata settimanale.',decimals:1})}
function drawExercise(name){const pts=[];[...(DB.sessions||[])].sort((a,b)=>(a.date||'').localeCompare(b.date||'')).forEach(s=>{const e=s.exercises.find(x=>x.name===name);if(!e)return;const z=e.sets.filter(x=>x.kg!=null).sort((a,b)=>b.kg-a.kg||b.reps-a.reps)[0];if(z)pts.push({label:s.date?fmtDate(s.date).slice(0,5):'',value:z.kg})});lineChart('exerciseChart',pts,{empty:'Nessun dato con carico.'})}
function drawCardioDistance(){const pts=(CARDIO?.activities||[]).slice().sort((a,b)=>(a.start_datetime||a.date||'').localeCompare(b.start_datetime||b.date||'')).filter(a=>a.distance_km!=null).map(a=>({label:fmtDate(a.date).slice(0,5),value:a.distance_km}));lineChart('cardioDistanceChart',pts,{zero:true,empty:'Nessuna corsa registrata.',decimals:1})}
function paceSeconds(p){if(!p)return null;const m=String(p).match(/(\d+):(\d+)/);return m?Number(m[1])*60+Number(m[2]):null}
function drawCardioPace(){const pts=(CARDIO?.activities||[]).slice().sort((a,b)=>(a.start_datetime||a.date||'').localeCompare(b.start_datetime||b.date||'')).map(a=>({label:fmtDate(a.date).slice(0,5),value:paceSeconds(a.pace)})).filter(x=>x.value!=null);lineChart('cardioPaceChart',pts,{empty:'Nessun passo medio disponibile.'})}
function switchTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));setTimeout(()=>{if(name==='dashboard'){drawCalories('kcalChart');drawWeight('weightChart')}if(name==='nutrition')drawCalories('kcalChartNutrition');if(name==='training'&&$('#exerciseSelect').value)drawExercise($('#exerciseSelect').value);if(name==='cardio'){drawCardioDistance();drawCardioPace()}if(name==='weight')drawWeight('weightChartFull')},20)}
Promise.all([
 fetch('data/workouts.json?v='+Date.now()).then(r=>r.json()),
 fetch('data/nutrition.json?v='+Date.now()).then(r=>r.json()),
 fetch('data/bodyweight.json?v='+Date.now()).then(r=>r.json()),
 fetch('data/cardio.json?v='+Date.now()).then(r=>r.json())
]).then(([w,n,b,c])=>{DB=w;NUTRITION=n;WEIGHT=b;CARDIO=c;render();$$('.tab').forEach(x=>x.addEventListener('click',()=>switchTab(x.dataset.tab)));$('#search').addEventListener('input',e=>renderSessions(e.target.value));$('#exerciseSelect').addEventListener('change',e=>drawExercise(e.target.value));$('#exportBtn').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({workouts:DB,nutrition:NUTRITION,bodyweight:WEIGHT,cardio:CARDIO},null,2)],{type:'application/json'}));a.download='fitness-export.json';a.click()});window.addEventListener('resize',()=>{const active=$('.tab.active')?.dataset.tab;switchTab(active||'dashboard')})});
